# Generated by Django 3.2 on 2021-05-01 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlRecord',
            fields=[
                ('short_url', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('original_url', models.URLField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_expiry', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
